### ISSUE TITLE
feature request: choose specific calendar

### ISSUE THREAD

**Issue by cbrown78501** [a11rew/calendar-focus-sync#1]
Hi! I'm looking for something like this, so I'm happy that you are developing it! However, I use several of my calendars for time blocking, and I can't have "Do Not Disturb" start for those events. Can I pick just one calendar to use with this app? That might make it workable for me. Thanks.

**Comment by a11rew** [comment]
Hi! Glad you've found this useful :) 

I could see this being a useful addition. I plan to work on an update soon fixing support in MacOS ~14.4.1 and could get this added in that update. I'll update you in this issue

Thanks for the feature request!
